batch_size: 32
cuda: true
data:
  data_type: None
  name: aist
  seq_len: 240
  test_dir: /host_data/van/Danceba/data/aistpp_test_full_wav # change
  train_dir: /host_data/van/Danceba/data/aistpp_train_wav # change
ds_rate: 8
epoch: 300
expname: cc_motion_gpt
external_wav: /host_data/van/Danceba/data/aistpp_music_feat_7.5fps # change
external_wav_rate: 1
global_vel: true
log_per_updates: 1
loss_weight:
  mse_weight: 1
move: 8
music_normalize: false
need_not_train_data: true # if train choose false
optimizer:
  kwargs:
    betas:
    - 0.5
    - 0.999
    lr: 0.0003
    weight_decay: 0
  schedular_kwargs:
    gamma: 0.1
    milestones:
    - 250
    - 400
  type: Adam
rotmat: false
save_per_epochs: 3
seed: 42
structure:
  down_half:
    commit: 0.02
    depth: 3
    dilation_growth_rate: 3
    downs_t:
    - 3
    emb_width: 512
    hvqvae_multipliers:
    - 1
    joint_channel: 3
    l_bins: 512
    l_mu: 0.99
    levels: 1
    m_conv: 1.0
    sample_length: 240
    strides_t:
    - 2
    use_bottleneck: true
    vqvae_reverse_decoder_dilation: true
    width: 512
  joint_channel: 3
  name: SepVQVAER
  up_half:
    commit: 0.02
    depth: 3
    dilation_growth_rate: 3
    downs_t:
    - 3
    emb_width: 512
    hvqvae_multipliers:
    - 1
    joint_channel: 3
    l_bins: 512
    l_mu: 0.99
    levels: 1
    m_conv: 1.0
    sample_length: 240
    strides_t:
    - 2
    use_bottleneck: true
    vqvae_reverse_decoder_dilation: true
    width: 512
  use_bottleneck: true
structure_generate:
  base:
    attn_pdrop: 0.1
    block_size: 29
    embd_pdrop: 0.1
    n_embd: 768
    n_head: 12
    n_layer: 6
    n_music: 438
    n_music_emb: 768
    resid_pdrop: 0.1
    vocab_size_down: 512
    vocab_size_up: 512
  block_size: 29
  head:
    attn_pdrop: 0.1
    block_size: 29
    embd_pdrop: 0.1
    n_embd: 768
    n_head: 12
    n_layer: 6
    resid_pdrop: 0.1
    vocab_size: 512
    vocab_size_down: 512
    vocab_size_up: 512
  n_music: 438
  n_music_emb: 768
  name: CrossCondGPT2
test_freq: 3
testing:
  ckpt_epoch: 0  # change
  height: 540
  width: 960
vqvae_weight: /host_data/van/Danceba/sep_vqvae_root/ckpt/epoch_500.pt
